
SET(LIBNAME TestGame)

SET(SOURCES TestGame.hpp TestGame.cpp)

ADD_LIBRARY(${LIBNAME} ${SOURCES})

TARGET_INCLUDE_DIRECTORIES(${LIBNAME} PUBLIC ${PROJECT_SOURCE_DIR}/Source/Engine/Core)
TARGET_LINK_LIBRARIES(${LIBNAME} IGame)
